### ISSUE TITLE
Escolha do tipo de combustivel

### ISSUE THREAD

**Issue by tugakufi** [denkyem/HA-DGEG-Combustiveis#1]
Grande trabalho esta muito bom.
Para ficar ainda melhor é possivel incluir a opção de poder escolher o tipo de combustível?

Gasóleo simples
Gasóleo especial
Gasolina simples 95
Gasolina 98

**Comment by denkyem** [comment]
Vou pensar nisso, eventualmente colocar algo como o ‘not_marcas’
