### ISSUE TITLE
Não faz update preços DGEG

### ISSUE THREAD

**Issue by fisiomacao** [denkyem/HA-DGEG-Combustiveis#2]
Boas.
Consegui configurar tudo no node red de acordo com o video do Jota Pombo, mas quando corro o node para fazer update aos preços DGEG fico com uma pequena marca amarela abaixo do node "Update Preços from DGEG" e não faz mais nada. Está assim há 4h. Junto anexo imagem.
![image](https://user-images.githubusercontent.com/88559763/151430144-d542c05f-7ab2-4eb2-a69b-2900f4c0f0e4.png)
Causas e como posso resolver?

**Comment by denkyem** [comment]
Quando inicias o Flow do update de preços, dá algum erro no debug?

**Comment by fisiomacao** [comment]
Dá sim. Desculpa mas não me tinha lembrado de ver. Dá este erro:
"Error: Table 'combustiveis.preco' doesn't exist"

**Comment by denkyem** [comment]
Inicia novamente o 'One time only'

**Comment by fisiomacao** [comment]
> 

Funcionou. Começou a correr o update de preços. Obrigado!
